### ISSUE TITLE
Render issue when using options in select-filter

### ISSUE THREAD

**Issue by adithewonderboy** [enso-ui/select#15]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
When using options to load a select-filter there are some issues with rendering, the labels are not shown, see images. This is not happening when using source to load the select.

### Steps to Reproduce
Configure a select-filter using options like this:
`:options="activeOptions"`
where activeOptions is defined like this:
`activeOptions: [
                {
                    value: 1,
                    label: 'check',
                },
                {
                    value: 2,
                    label: 'times',
                },
            ],`
This is not happening if you load select vie source:
`source="models.groups.options"`

### Expected behavior
![image](https://user-images.githubusercontent.com/58045802/76878105-060df480-687d-11ea-8659-ea31069d176e.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/58045802/76878151-19b95b00-687d-11ea-99e0-04d56aa1892b.png)

**Comment by aocneanu** [comment]
The select component has a `track-by` prop that defaults to `id` and a `label` prop that defaults to `name`. This way it works with most of the BE models without customisations.

You can either change value -> id and label -> name or pass the customized props to vue-select

**Comment by adithewonderboy** [comment]
Thanks!
