### ISSUE TITLE
cursive writing/font not supported on dropdown

### ISSUE THREAD

**Issue by YacoubBelaoura** [enso-ui/select#2]
This is  a **bug ?**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

the `vue-select` dropdown  dont suport `cursive writing` fonts and languages like 'arabic'
example screenshots 
![deco01](https://user-images.githubusercontent.com/18699402/55404796-9a8a2480-5550-11e9-8ef9-f84893bd61e3.png)
![decomposed](https://user-images.githubusercontent.com/18699402/55404797-9a8a2480-5550-11e9-8cc5-c9a600a9d1b4.png)

### Steps to Reproduce

1. visit `Edit Permission` and change language to arabic "use cursive writing" and click on type select dropdown menu, you will notice it separate characters.

### Expected behavior

for `cursive fonts` it should keep it like it is
![normalLang](https://user-images.githubusercontent.com/18699402/55405246-88f54c80-5551-11e9-9af2-caf6b4c52a2a.png)

### Actual behavior

![decomposed](https://user-images.githubusercontent.com/18699402/55404797-9a8a2480-5550-11e9-8cc5-c9a600a9d1b4.png)

## reason ?
the `<b>` tag around `RegExp ` text
```javascript
        highlight(label) {
            return label.replace(
                new RegExp(`(${this.query})`, 'gi'), '<b>$1</b>',
            );
        },
```

**Comment by aocneanu** [comment]
If we remove the `<b>` how do we highlight the matched string from an option?

**Comment by YacoubBelaoura** [comment]
my solution is to use this `Zero-width joiner` add `&#x200d;` after `<b>` tag
```javascript
        highlight(label) {
            return label.replace(
                new RegExp(`(${this.query})`, 'gi'), '&#x200d;<b>$1</b>',
            );
```

here is the output. 
![output](https://user-images.githubusercontent.com/18699402/56849505-2fccce80-68ed-11e9-8a2a-48d9c04fd337.gif)

**Comment by aocneanu** [comment]
you mean before the `<b>` tag?

So just to be clear, doing this fixes the reported problem?

**Comment by YacoubBelaoura** [comment]
yes.
yes it's a workaround, but it still has problem and that is "the letter always stay in connected state"

but it's better than before

**Comment by YacoubBelaoura** [comment]
the problem is that this function will inject empty `<b>` tags in select options. 
```javascript
        highlight(label) {
            return label.replace(
                new RegExp(`(${this.query})`, 'gi'), '<b>$1</b>',
            );
        },
```
 like here:
```html
<span>‍<b></b>ق‍<b></b>ر‍<b></b>ا‍<b></b>ء‍<b></b>ة‍<b></b></span>
```
so the fix is only to inject `<b>` tag when there is a query.
so here is the working fix:
```javascript
        highlight(label) {
            if (this.query.length > 0) {
                return label.replace(
                    new RegExp(`(${this.query})`, 'gi'), '<b>$1</b>',
                );
            } else {
                return label;
            }
        },
```
i will make a PR if you approve.

**Comment by aocneanu** [comment]
@YacoubBelaoura, I forgot about this, do a PR.

Thanks.

PS use a ternary instead of if else.
