### ISSUE TITLE
The style of the change change

### ISSUE THREAD

**Issue by heyner29** [enso-ui/select#7]
This is  a **bug | feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

Hello, I think that with the RTL update, the CSS style of the select is ruined a bit

![1 Calendar](https://user-images.githubusercontent.com/12703614/57053428-93d7f580-6c53-11e9-83c0-20dd855acc0a.png)
![2 Select Table Example](https://user-images.githubusercontent.com/12703614/57053429-93d7f580-6c53-11e9-977a-b31626e2af46.png)
![3 Select Lentgh table](https://user-images.githubusercontent.com/12703614/57053430-93d7f580-6c53-11e9-838c-76c6b74a08b7.png)

### Steps to Reproduce
On the table example page, you can see that the arrow and spam select are not in place.

**Comment by aocneanu** [comment]
`yarn upgrade`

**Comment by aocneanu** [comment]
Will close due to inactivity
